# -*- coding: utf-8 -*-
"""Script_XPT_a_CSV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17X9ZJqUUoy3pBd6X5qe1szemdR36s7FA
"""

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

#Es necesario descomprimir la carpeta que contiene el archivo
xpt_file = "/content/drive/MyDrive/10ª Edición Máster en Data Science/TFM/Dataset_sin_tratar.XPT"

df = pd.read_sas(xpt_file, format='xport', encoding='latin1')

csv_file = "/content/drive/MyDrive/10ª Edición Máster en Data Science/TFM/Dataset_sin_tratar.CSV"
df.to_csv(csv_file, index=False)
print(f"Archivo CSV creado: {csv_file}")

csv_file = "/content/drive/MyDrive/10ª Edición Máster en Data Science/LLCP2015.CSV"
df = pd.read_csv(csv_file, encoding='latin1')
df.info()